version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qr-scanner-app
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./storage:/var/www/html/storage
      - ./database:/var/www/html/database
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=http://localhost
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - QUEUE_CONNECTION=sync
      - LOG_CHANNEL=stack
    networks:
      - qr-scanner-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  qr-scanner-network:
    driver: bridge

volumes:
  storage:
  database:
