version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qr-scanner-prod
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./storage:/var/www/html/storage
      - ./database:/var/www/html/database
      - ./ssl:/etc/nginx/ssl:ro
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=https://yourdomain.com
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - QUEUE_CONNECTION=sync
      - LOG_CHANNEL=stack
      - SESSION_SECURE_COOKIE=true
    networks:
      - qr-scanner-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qr-scanner.rule=Host(`yourdomain.com`)"
      - "traefik.http.routers.qr-scanner.tls=true"
      - "traefik.http.routers.qr-scanner.tls.certresolver=letsencrypt"

networks:
  qr-scanner-network:
    driver: bridge

volumes:
  storage:
  database:
